# Enable GitHub Sponsors
github: [piyush295]

# Optional funding platforms (leave empty if not used)
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:

# Custom funding links (optional)
custom: []
